version: '3.2'
services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - .configs/mongo.env
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .configs/mongo-express.env
    depends_on:
      - mongo
  graphql-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .configs/backend.env
    container_name: graphql-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
